version: "3.1"

services:
  node-app:
    restart: always
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
      - DB_REDIS_HOST=redis
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
#      - pgadmin
    links:
      - postgres
      - redis
#      - pgadmin

  postgres:
    image: postgres:11-alpine
    env_file:
      - ./.env
    volumes:
      - ./.db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - ./.db/redis:/data
